### ISSUE TITLE
run.sh error: The command '[...]' returned a non-zero code: 100

### ISSUE THREAD

**Issue by civersen** [silarsis/docker-proxy#10]
Hi,
I'm getting this error when attempting to start the docker-proxy (on a work network behind a proxy). Any ideas? 
```
[...]/docker-proxy (master)$ sudo ./run.sh 

Sending build context to Docker daemon 429.1 kB
Step 0 : FROM silarsis/base
 ---> b1e0761ebf68
Step 1 : MAINTAINER Kevin Littlejohn <kevin@littlejohn.id.au>
 ---> Using cache
 ---> bd1c2e9d8109
Step 2 : RUN apt-get -yq update
 ---> Using cache
 ---> f893ebae8e59
Step 3 : RUN apt-get -yq install squid iptables
 ---> Running in 9f6dc112263e
The command '/bin/sh -c apt-get -yq install squid iptables' returned a non-zero code: 100
```

**Comment by silarsis** [comment]
My initial reaction would be that perhaps apt-get isn't able to get to the
rest of the world. If you run a `docker run -it silarsis/base` and try an
apt-get update ; apt-get upgrade in there, that may show it up.

Likely causes would include that you've moved your laptop without
restarting your guest operating system (docker-machine stop; docker-machine
start if i recall correctly) and it's networking is confused, or that your
work proxy is requiring some form of login.

KJL

**Comment by civersen** [comment]
Thanks, you got me to double check and I had misconfigured the http_proxy env.

Cheers
