### ISSUE TITLE
help! i somehow set this to run on startup but i'm not sure how

### ISSUE THREAD

**Issue by SlimeQ** [silarsis/docker-proxy#13]
i installed this on my work machine when i was tinkering with docker dns stuff, but now it binds to all the ports i need when i start docker and and i'm not sure how to get rid of it.

![screenshot from 2016-01-13 11 47 41](https://cloud.githubusercontent.com/assets/3934698/12301045/12c73838-b9ec-11e5-8fcc-b99bb71f9e45.png)

an attempt to find the executable using `ll /proc/$(ps aux | grep docker-proxy | head -n 1 | cut -d ' ' -f 7)/exe` just shows the docker executable

![screenshot from 2016-01-13 11 57 49](https://cloud.githubusercontent.com/assets/3934698/12301240/f8d9c26e-b9ec-11e5-9339-9d03ac41e6ba.png)

this is killing me, any ideas?

**Comment by silarsis** [comment]
try `docker ps` - that should show you running docker containers, and
`docker kill` will let you kill them. You _should_ be able to just `docker
kill docker-proxy` to clean it up, by rights.

KJL

**Comment by SlimeQ** [comment]
i wish it were that simple. docker ps shows no docker-proxy containers __and__ docker images shows no docker-proxy images. i'm at a total loss as to why/how this is happening

**Comment by silarsis** [comment]
That's _very_ strange. My only suggestions would go toward uninstalling
docker and re-installing, and/or re-doing your machine. Or perhaps log it
as a bug with docker?

**Comment by nicorevin** [comment]
No worries! It's just name ambiguity. http://windsock.io/the-docker-proxy/
