### ISSUE TITLE
Unable to find a source package for squid3

### ISSUE THREAD

**Issue by Malvineous** [silarsis/docker-proxy#21]
The `docker build` step currently fails with an error:

    E: Unable to find a source package for squid3

This is apparently because the Docker image for Ubuntu 14.04 was at some point changed to comment out the `deb-src` lines in `sources.list`, as most Dockerfiles did not need source packages and it was slowing down `apt-get update`.

The problem can be fixed by adding this line before the `apt-get` one:

    RUN sed -i 's/^# deb-src/deb-src/' /etc/apt/sources.list

This uncomments the `deb-src` lines and allows the `squid3` source package to be located.

**Comment by hoijui** [comment]
i can confirm this, both the issue and the solution. thanks you @Malvineous :-)
i made a pull request with this fix:
https://github.com/silarsis/docker-proxy/pull/22

**Comment by silarsis** [comment]
Thanks for the PR, have merged :)
