### ISSUE TITLE
add link to docker hub

### ISSUE THREAD

**Issue by thomasleveil** [silarsis/docker-proxy#7]
Would you mind adding [the link to docker hub](https://hub.docker.com/r/silarsis/docker-proxy/) on this project description? It would make it easier for us to go back and forth between github and hub.

![2015-08-29_15h31_11](https://cloud.githubusercontent.com/assets/42300/9562140/533b4fac-4e63-11e5-94ac-10020a1afa21.png)

and kudos for making this docker image public :+1:

**Comment by silarsis** [comment]
Done :)
